["animate_frame"] = {
    ["sprite_count"] = 1,
    [0] = {
        [1] = {
            ["posx"] = 421,
            ["scax"] = 1,
            ["rota"] = 0,
            ["scay"] = 1,
            ["rect"] = {
                ["heig"] = 166,
                ["path"] = "boy.png",
                ["orix"] = 101,
                ["widt"] = 145,
                ["oriy"] = 714,
            },
            ["id"] = 5,
            ["posy"] = 241,
        },
        [2] = {
            ["posx"] = 421,
            ["scax"] = 1,
            ["rota"] = 0,
            ["scay"] = 1,
            ["rect"] = {
                ["heig"] = 158,
                ["path"] = "boy.png",
                ["orix"] = 381,
                ["widt"] = 158,
                ["oriy"] = 504,
            },
            ["id"] = 11,
            ["posy"] = 241,
        },
        [0] = {
            ["posx"] = 421,
            ["scax"] = 1,
            ["rota"] = 0,
            ["scay"] = 1,
            ["rect"] = {
                ["heig"] = 151,
                ["path"] = "boy.png",
                ["orix"] = 248,
                ["widt"] = 118,
                ["oriy"] = 714,
            },
            ["id"] = 0,
            ["posy"] = 241,
        },
    },
    ["basey"] = 57,
    ["basex"] = 88,
},
